# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: "ruby"
script: "bundle exec rake"
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
notifications:
  irc: "irc.freenode.org#savon"
